export type LessonRecordStatus = "draft" | "pending_feedback" | "submitted" | "completed" | "cancelled";

export type LessonRecord = {
  id: string;
  scheduleId?: string;
  courseId?: string;
  courseName?: string;
  classId?: string;
  className: string;
  studentId?: string;
  studentName: string;
  teacherId: string;
  teacherName: string;
  date: string;
  startTime?: string;
  endTime?: string;
  timeString?: string;
  classroom?: string;
  duration?: number;
  topic: string;
  attendance: "present" | "absent" | "student_leave" | "teacher_leave";
  status: LessonRecordStatus;
  feedbackStatus: "submitted" | "pending";
  creditsConsumed: number;
  performance?: string;
  knowledgeMastery?: string;
  homework?: string;
  nextPlan?: string;
  internalNotes?: string;
  aiSummary?: string;
  deductionStatus?: "pending" | "deducted";
  needAdvisorFollowUp?: boolean;
  syncToParent?: boolean;
  updatedAt?: string;
};

export type LeaveRecord = {
  id: string;
  scheduleId?: string;
  lessonRecordId?: string;
  type: "student_leave" | "teacher_leave" | "reschedule" | "cancel" | "cancellation" | "makeup";
  requestType?: "student_leave" | "teacher_leave" | "reschedule" | "cancellation" | "makeup";
  studentId?: string;
  studentName?: string;
  teacherId?: string;
  teacherName?: string;
  classId?: string;
  className?: string;
  courseId?: string;
  courseName?: string;
  originalDate: string;
  originalStartTime?: string;
  originalEndTime?: string;
  originalTime?: string;
  makeupDate?: string;
  newDate?: string;
  newStartTime?: string;
  newEndTime?: string;
  reason: string;
  deductCredit: boolean;
  needMakeup?: boolean;
  status: "pending" | "approved" | "rejected" | "makeup_pending" | "makeup_scheduled" | "makeup_completed" | "completed" | "parent_notified" | "cancelled";
  approvalNote?: string;
  rejectReason?: string;
  parentNotified?: boolean;
  notifyStatus: "notified" | "pending";
  makeupScheduleId?: string;
  createdBy?: string;
  approvedBy?: string;
  approvedAt?: string;
  createdAt?: string;
  updatedAt?: string;
};

export type Assessment = {
  id: string;
  studentName: string;
  courseName: string;
  title: string;
  teacherName: string;
  dueDate: string;
  submitStatus: "submitted" | "pending" | "late";
  gradeStatus: "graded" | "pending";
  score?: number;
};
